services:
  postgres:
    ports: !override
      - "15432:5432"

  redis:
    ports: !override
      - "16379:6379"

  prometheus:
    ports: !override
      - "19090:9090"

  grafana:
    ports: !override
      - "13000:3000"
